version: '3.7'
services:
    db:
        image: mysql
        container_name: db
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        networks:
            - db
    php:
        container_name: php
        build: docker/php
        ports:
            - 9000:9000
        volumes:
            - ./app:/var/www/app:cached
            - ./docker/logs/app:/var/www/app/var/log:cached
            - ./docker/php/app.ini:/usr/local/etc/php/conf.d/app.ini
        networks:
            - db
            - web
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
            - ./docker/logs/nginx:/var/log/nginx:cached
            - ./app:/var/www/app:cached
        networks:
            - web
    node:
        image: node:13-alpine
        container_name: node
        ports:
            - 8080:8080
        volumes:
            - ./app:/app
        working_dir: /app
        tty: true
networks:
    db:
    web: